set ERLANG_HOME=c:\Program Files\erl-24.1.7
set RABBITMQ_NODE_PORT=5672
set RABBITMQ_DIST_PORT=25672
set RABBITMQ_NODENAME=rabbit1@localhost
set RABBITMQ_MNESIA_BASE=C:\data\rabbit1
set RABBITMQ_MNESIA_DIR=C:\data\rabbit1\data
set RABBITMQ_LOG_BASE=C:\data\rabbit1\logs
set RABBITMQ_CONFIG_FILE=C:\RabbitMQ\rabbitmq_server-3.9.10\config\rabbitmq
set RABBITMQ_ENABLED_PLUGINS_FILE=C:\data\rabbit1\enabled_plugins
